### ISSUE TITLE
Question concerning the Filter trait

### ISSUE THREAD

**Issue by flosse** [signalo/signalo#2]
Why is the `Filter` trait defined like this
```rust
pub trait Filter<Input>: Sized {
    type Output;
    fn filter(&mut self, input: Input) -> Self::Output;
}
```

instead of 

```rust
pub trait Filter<Input,Output>: Sized {
    fn filter(&mut self, input: Input) -> Output;
}
```
?

**Comment by flosse** [comment]
Thanks for your reply! It's interesting to see others code :)

> Is there anything you want to do that `Filter<Input>` (vs. `Filter<Input, Output>`) prevents you from doing?

No, not at all. I was just curious about your approach because I [defined a similar trait](https://docs.rs/msr/0.1.0/msr/trait.Controller.html) in the [msr](https://github.com/slowtec/msr) and so I'm interested to learn from your rust skills :)

**Comment by regexident** [comment]
I took inspiration from stdlib's `Add<T>`, `Mul<T>` & Co and so far it worked flawlessly for me.
