### ISSUE TITLE
Current version not compiling

### ISSUE THREAD

**Issue by svechinsky** [signalo/signalo#86]
When trying to add Signalo as a dependency to a project I get the following compilation errors:

error[E0277]: the trait bound `generic_array::GenericArray<T, N>: arraydeque::Array` is not satisfied
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/signalo_filters-0.5.1/src/convolve/mod.rs:38:5
   |
38 |     pub taps: ArrayDeque<GenericArray<T, N>, Wrapping>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `arraydeque::Array` is not implemented for `generic_array::GenericArray<T, N>`
   | 
  ::: /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/arraydeque-0.4.5/src/lib.rs:97:26
   |
97 | pub struct ArrayDeque<A: Array, B: Behavior = Saturating> {
   |                          ----- required by this bound in `arraydeque::ArrayDeque`

error[E0277]: the trait bound `generic_array::GenericArray<T, N>: arraydeque::Array` is not satisfied
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/signalo_filters-0.5.1/src/delay.rs:25:5
   |
25 |     pub taps: ArrayDeque<GenericArray<T, N>, Wrapping>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `arraydeque::Array` is not implemented for `generic_array::GenericArray<T, N>`
   | 
  ::: /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/arraydeque-0.4.5/src/lib.rs:97:26
   |
97 | pub struct ArrayDeque<A: Array, B: Behavior = Saturating> {
   |                          ----- required by this bound in `arraydeque::ArrayDeque`

error[E0277]: the trait bound `generic_array::GenericArray<T, N>: arraydeque::Array` is not satisfied
  --> /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/signalo_filters-0.5.1/src/mean/mean.rs:26:5
   |
26 |     pub taps: ArrayDeque<GenericArray<T, N>, Wrapping>,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `arraydeque::Array` is not implemented for `generic_array::GenericArray<T, N>`
   | 
  ::: /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/arraydeque-0.4.5/src/lib.rs:97:26
   |
97 | pub struct ArrayDeque<A: Array, B: Behavior = Saturating> {
   |                          ----- required by this bound in `arraydeque::ArrayDeque`

**Comment by regexident** [comment]
Hi @svechinsky,

how did you build the project? It's compiling just fine with `cargo build` for me. 🤔

**Comment by svechinsky** [comment]
I just included it into another project via cargo.toml

**Comment by regexident** [comment]
I can reproduce it now, thanks @svechinsky!

To be honest I'm not sure what's going on. Will need more digging. 😕

**Comment by lynlog19** [comment]
I am also getting the same error after putting 'signalo = "0.5.0"' into my Cargo.toml

**Comment by regexident** [comment]
Looks like `ArrayDeque` added constraints, breaking semver, in an attempt to support const generics, which broke several of `signalo`'s filters.

Since I had planned to migrate to const generics for quite a while anyway I removed `GenericArray`/`ArrayDeque` in favor of `[T; const N: usize]` and `signalo_filters::circular_buffer::CircularBuffer`.

**Comment by regexident** [comment]
A corresponding version has been published.
